using System;
using System.Globalization;
using System.Linq;
using Comsec.SqlPrune.Models;
using Sugar;

namespace Comsec.SqlPrune
{
    /// <summary>
    /// Helper class to centralise the logic used to validate and extract the datbase name and creation date 
    /// from the name of Microsoft SQL .bak files as generated by Microsoft SQL Management Studio's backup tasks.
    /// </summary>
    public static class BakFilenameExtractor
    {
        /// <summary>
        /// Validates the name of the MS SQL bak file and extracts:
        /// - the database name
        /// - the date the file was created.
        /// </summary>
        /// <param name="filename">The database filename (e.g. "db1_backup_2010_11_20_010203_1234567.bak").</param>
        /// <param name="databaseName">The name of the database (extracted form the <see cref="filename"/>).</param>
        /// <param name="created">The creation date and time of the file (extracted from the <see cref="filename"/>).</param>
        /// <returns></returns>
        public static bool ValidateFilenameAndExtract(string filename, out string databaseName, out DateTime created)
        {
            var isValid = false;

            databaseName = null;
            created = new DateTime();

            if (!string.IsNullOrEmpty(filename) && filename.EndsWith(".bak", StringComparison.OrdinalIgnoreCase))
            {
                var fileName = filename.SubstringAfterLastChar(@"\");

                var numberOfUnderscores = fileName.Count(x => x == '_');

                var backupPosition = fileName.IndexOf("_backup_", StringComparison.InvariantCultureIgnoreCase);

                if (numberOfUnderscores == 6 && backupPosition >= 0)
                {
                    databaseName = fileName.Substring(0, backupPosition);

                    var datetimeComponent = fileName.Substring(backupPosition + 8, 17);

                    created = DateTime.ParseExact(datetimeComponent, "yyyy_MM_dd_HHmmss", null, DateTimeStyles.AssumeUniversal);

                    isValid = true;
                }
            }

            return isValid;
        }

        /// <summary>
        /// Validates the name of the MS SQL bak file and extracts:
        /// - the database name
        /// - the date the file was created.
        /// </summary>
        /// <param name="path">The path.</param>
        /// <param name="model">The model.</param>
        /// <returns></returns>
        public static bool ValidateFilenameAndExtract(string path, out BakModel model)
        {
            string name;
            DateTime created;
            
            if (ValidateFilenameAndExtract(path, out name, out created))
            {
                model = new BakModel {Path = path, DatabaseName = name, Created = created};

                return true;
            }
            
            model = null;
            return false;
        }
    }
}
